# Pruebas para Data Thefts

## Inicialización

### Importar dependencias

In [1]:
# Dependencias externas
import pandas as pd

# Dependencias locales
from LabelerV2.modules.matcher import process_tagging
from LabelerV2.modules.config_loader import load_config
from LabelerV2.modules.file_handler import load_csv

from verificator import analyze_labels_in_dataframe

### Cargar configuración

In [2]:
# Cargar configuración
config = load_config(r'LabelerV2/labeler_config.json', "Bot-IoT")

# Mostrar configuración
config

{'Bot-IoT': {'target_csv_key_columns': ['src_ip',
   'dst_ip',
   'src_port',
   'dst_port',
   'src2dst_packets',
   'dst2src_packets'],
  'reference_csv_key_columns': ['saddr',
   'daddr',
   'sport',
   'dport',
   'spkts',
   'dpkts'],
  'column_mapping': {'src_ip': 'saddr',
   'dst_ip': 'daddr',
   'src_port': 'sport',
   'dst_port': 'dport',
   'src2dst_packets': 'spkts',
   'dst2src_packets': 'dpkts'},
  'ports_columns': ['src_port', 'dst_port', 'sport', 'dport'],
  'columns_to_copy': ['attack', 'category', 'subcategory'],
  'labeling_files': {'data_theft': 'data_exfiltration',
   'keylogging': 'keylogging',
   'http_ddos': 'ddos_http',
   'udp_ddos': 'ddos_udp',
   'tcp_ddos': 'ddos_tcp',
   'http_dos': 'dos_http',
   'udp_dos': 'dos_udp',
   'tcp_dos': 'dos_tcp',
   'osscan': 'os_scan',
   'servicescan': 'service_scan'}}}

## Cargar DataFrames

### Cargar DataFrames a etiquetar

In [3]:
# Cargar DataFrame N°1
df_to_label_01 = load_csv(r'CSVs/f/USACH/Ayudantias/Investigacion-Redes/PCAPs/Bot-IoT/Theft/Data_Exfiltration/IoT_Dataset_data_theft__00001_20180618110503.csv')
df_to_label_01.head(5)

,id,expiration_id,src_ip,src_mac,src_oui,src_port,dst_ip,dst_mac,dst_oui,dst_port,...,dst2src_fin_packets,application_name,application_category_name,application_is_guessed,application_confidence,requested_server_name,client_fingerprint,server_fingerprint,user_agent,content_type
0,0,0,192.168.100.46,be:ff:34:42:10:01,be:ff:34,80,192.168.100.5,ae:bb:10:44:55:60,ae:bb:10,80,...,0,Unknown,Unspecified,0,0,NaN,NaN,NaN,NaN,NaN
1,1,0,192.168.100.46,be:ff:34:42:10:01,be:ff:34,80,192.168.100.5,ae:bb:10:44:55:60,ae:bb:10,80,...,0,HTTP,Web,1,1,NaN,NaN,NaN,NaN,NaN
2,2,0,192.168.100.3,00:50:56:be:26:db,00:50:56,60864,172.217.25.138,00:50:56:be:b5:f6,00:50:56,443,...,1,TLS,Web,0,6,NaN,NaN,NaN,NaN,NaN
3,3,0,192.168.100.7,fa:cb:34:12:44:59,fa:cb:34,365,192.168.100.3,ba:ba:ca:6a:00:12,ba:ba:ca,565,...,0,Unknown,Unspecified,0,0,NaN,NaN,NaN,NaN,NaN
4,4,0,192.168.100.6,00:50:56:be:4f:b7,00:50:56,138,192.168.100.255,ff:ff:ff:ff:ff:ff,ff:ff:ff,138,...,0,NetBIOS.SMBv1,System,0,6,wininst,NaN,NaN,NaN,NaN

In [4]:
# Cargar DataFrame N°2
df_to_label_02 = load_csv(r'CSVs/f/USACH/Ayudantias/Investigacion-Redes/PCAPs/Bot-IoT/Theft/Data_Exfiltration/IoT_Dataset_data_theft__00002_20180618111101.csv')
df_to_label_02.head(5)

,id,expiration_id,src_ip,src_mac,src_oui,src_port,dst_ip,dst_mac,dst_oui,dst_port,...,dst2src_fin_packets,application_name,application_category_name,application_is_guessed,application_confidence,requested_server_name,client_fingerprint,server_fingerprint,user_agent,content_type
0,0,0,192.168.100.46,be:ff:34:42:10:01,be:ff:34,80,192.168.100.5,ae:bb:10:44:55:60,ae:bb:10,80,...,0,HTTP,Web,1,1,NaN,NaN,NaN,NaN,NaN
1,1,0,192.168.100.7,fa:cb:34:12:44:59,fa:cb:34,365,192.168.100.3,ba:ba:ca:6a:00:12,ba:ba:ca,565,...,0,Unknown,Unspecified,0,0,NaN,NaN,NaN,NaN,NaN
2,2,0,192.168.100.3,00:50:56:be:26:db,00:50:56,50850,13.54.166.67,00:50:56:be:b5:f6,00:50:56,8883,...,0,TLS,Web,0,6,NaN,NaN,NaN,NaN,NaN
3,3,0,192.168.100.46,be:ff:34:42:10:01,be:ff:34,3456,192.168.100.5,ae:bb:10:44:55:60,ae:bb:10,80,...,0,Unknown,Unspecified,0,0,NaN,NaN,NaN,NaN,NaN
4,4,0,192.168.100.55,ff:ea:24:21:12:13,ff:ea:24,8080,192.168.100.3,fa:cb:34:12:44:59,fa:cb:34,80,...,0,HTTP,Web,1,1,NaN,NaN,NaN,NaN,NaN

In [5]:
# Cargar DataFrame N°3
df_to_label_03 = load_csv(r'CSVs/f/USACH/Ayudantias/Investigacion-Redes/PCAPs/Bot-IoT/Theft/Data_Exfiltration/IoT_Dataset_data_theft__00003_20180618111233.csv')
df_to_label_03.head(5)

,id,expiration_id,src_ip,src_mac,src_oui,src_port,dst_ip,dst_mac,dst_oui,dst_port,...,dst2src_fin_packets,application_name,application_category_name,application_is_guessed,application_confidence,requested_server_name,client_fingerprint,server_fingerprint,user_agent,content_type
0,0,0,192.168.100.3,00:50:56:be:26:db,00:50:56,50032,192.168.100.150,00:50:56:be:02:54,00:50:56,4433,...,0,Unknown,Unspecified,0,0,NaN,NaN,NaN,NaN,NaN
1,1,0,192.168.100.6,bb:aa:cc:98:55:43,bb:aa:cc,80,192.168.100.3,fa:cb:34:12:44:59,fa:cb:34,80,...,0,HTTP,Web,1,1,NaN,NaN,NaN,NaN,NaN
2,2,0,192.168.100.3,fa:cb:34:12:44:59,fa:cb:34,80,192.168.100.55,ff:ea:24:21:12:13,ff:ea:24,8080,...,0,HTTP,Web,1,1,NaN,NaN,NaN,NaN,NaN
3,3,0,192.168.100.149,00:50:56:be:c0:38,00:50:56,4444,192.168.100.6,00:50:56:be:4f:b7,00:50:56,49160,...,0,Unknown,Unspecified,0,0,NaN,NaN,NaN,NaN,NaN
4,4,0,192.168.100.46,be:ff:34:42:10:01,be:ff:34,3456,192.168.100.5,ae:bb:10:44:55:60,ae:bb:10,80,...,0,Unknown,Unspecified,0,0,NaN,NaN,NaN,NaN,NaN

In [6]:
# Cargar DataFrame N°4
df_to_label_04 = load_csv(r'CSVs/f/USACH/Ayudantias/Investigacion-Redes/PCAPs/Bot-IoT/Theft/Data_Exfiltration/IoT_Dataset_data_theft__00004_20180618111334.csv')
df_to_label_04.head(5)

,id,expiration_id,src_ip,src_mac,src_oui,src_port,dst_ip,dst_mac,dst_oui,dst_port,...,dst2src_fin_packets,application_name,application_category_name,application_is_guessed,application_confidence,requested_server_name,client_fingerprint,server_fingerprint,user_agent,content_type
0,0,0,192.168.100.46,be:ff:34:42:10:01,be:ff:34,3456,192.168.100.5,ae:bb:10:44:55:60,ae:bb:10,80,...,0,Unknown,Unspecified,0,0,NaN,NaN,NaN,NaN,NaN
1,1,0,192.168.100.6,00:50:56:be:4f:b7,00:50:56,49160,192.168.100.149,00:50:56:be:c0:38,00:50:56,4444,...,0,Unknown,Unspecified,0,0,NaN,NaN,NaN,NaN,NaN
2,2,0,192.168.100.46,be:ff:34:42:10:01,be:ff:34,80,192.168.100.5,ae:bb:10:44:55:60,ae:bb:10,80,...,0,HTTP,Web,1,1,NaN,NaN,NaN,NaN,NaN
3,3,0,192.168.100.6,bb:aa:cc:98:55:43,bb:aa:cc,80,192.168.100.3,fa:cb:34:12:44:59,fa:cb:34,80,...,0,HTTP,Web,1,1,NaN,NaN,NaN,NaN,NaN
4,4,0,192.168.100.3,fa:cb:34:12:44:59,fa:cb:34,80,192.168.100.55,ff:ea:24:21:12:13,ff:ea:24,8080,...,0,HTTP,Web,1,1,NaN,NaN,NaN,NaN,NaN

In [7]:
# Cargar DataFrame N°5
df_to_label_05 = load_csv(r'CSVs/f/USACH/Ayudantias/Investigacion-Redes/PCAPs/Bot-IoT/Theft/Data_Exfiltration/IoT_Dataset_data_theft__00005_20180618111434.csv')
df_to_label_05.head(5)

,id,expiration_id,src_ip,src_mac,src_oui,src_port,dst_ip,dst_mac,dst_oui,dst_port,...,dst2src_fin_packets,application_name,application_category_name,application_is_guessed,application_confidence,requested_server_name,client_fingerprint,server_fingerprint,user_agent,content_type
0,0,0,192.168.100.6,00:50:56:be:4f:b7,00:50:56,49160,192.168.100.149,00:50:56:be:c0:38,00:50:56,4444,...,0,Unknown,Unspecified,0,0,NaN,NaN,NaN,NaN,NaN
1,1,0,192.168.100.46,be:ff:34:42:10:01,be:ff:34,80,192.168.100.5,ae:bb:10:44:55:60,ae:bb:10,80,...,0,HTTP,Web,1,1,NaN,NaN,NaN,NaN,NaN
2,2,0,192.168.100.46,be:ff:34:42:10:01,be:ff:34,80,192.168.100.5,ae:bb:10:44:55:60,ae:bb:10,80,...,0,Unknown,Unspecified,0,0,NaN,NaN,NaN,NaN,NaN
3,3,0,192.168.100.6,bb:aa:cc:98:55:43,bb:aa:cc,80,192.168.100.3,fa:cb:34:12:44:59,fa:cb:34,80,...,0,HTTP,Web,1,1,NaN,NaN,NaN,NaN,NaN
4,4,0,192.168.100.7,fa:cb:34:12:44:59,fa:cb:34,365,192.168.100.3,ba:ba:ca:6a:00:12,ba:ba:ca,565,...,0,Unknown,Unspecified,0,0,NaN,NaN,NaN,NaN,NaN

In [8]:
# Cargar DataFrame N°6
df_to_label_06 = load_csv(r'CSVs/f/USACH/Ayudantias/Investigacion-Redes/PCAPs/Bot-IoT/Theft/Data_Exfiltration/IoT_Dataset_data_theft__00006_20180618111532.csv')
df_to_label_06.head(5)

,id,expiration_id,src_ip,src_mac,src_oui,src_port,dst_ip,dst_mac,dst_oui,dst_port,...,dst2src_fin_packets,application_name,application_category_name,application_is_guessed,application_confidence,requested_server_name,client_fingerprint,server_fingerprint,user_agent,content_type
0,0,0,192.168.100.46,be:ff:34:42:10:01,be:ff:34,80,192.168.100.5,ae:bb:10:44:55:60,ae:bb:10,80,...,0,Unknown,Unspecified,0,0,NaN,NaN,NaN,NaN,NaN
1,1,0,192.168.100.6,bb:aa:cc:98:55:43,bb:aa:cc,80,192.168.100.3,fa:cb:34:12:44:59,fa:cb:34,80,...,0,HTTP,Web,1,1,NaN,NaN,NaN,NaN,NaN
2,2,0,192.168.100.3,00:50:56:be:26:db,00:50:56,50032,192.168.100.150,00:50:56:be:02:54,00:50:56,4433,...,0,Unknown,Unspecified,0,0,NaN,NaN,NaN,NaN,NaN
3,3,0,192.168.100.6,00:50:56:be:4f:b7,00:50:56,138,192.168.100.255,ff:ff:ff:ff:ff:ff,ff:ff:ff,138,...,0,NetBIOS.SMBv1,System,0,6,wininst,NaN,NaN,NaN,NaN
4,4,0,192.168.100.149,00:50:56:be:c0:38,00:50:56,4444,192.168.100.6,00:50:56:be:4f:b7,00:50:56,49160,...,0,Unknown,Unspecified,0,0,NaN,NaN,NaN,NaN,NaN

In [9]:
# Cargar DataFrame N°7
df_to_label_07 = load_csv(r'CSVs/f/USACH/Ayudantias/Investigacion-Redes/PCAPs/Bot-IoT/Theft/Data_Exfiltration/IoT_Dataset_data_theft__00007_20180618111630.csv')
df_to_label_07.head(5)

,id,expiration_id,src_ip,src_mac,src_oui,src_port,dst_ip,dst_mac,dst_oui,dst_port,...,dst2src_fin_packets,application_name,application_category_name,application_is_guessed,application_confidence,requested_server_name,client_fingerprint,server_fingerprint,user_agent,content_type
0,0,0,192.168.100.6,00:50:56:be:4f:b7,00:50:56,49160,192.168.100.149,00:50:56:be:c0:38,00:50:56,4444,...,0,Unknown,Unspecified,0,0,NaN,NaN,NaN,NaN,NaN
1,1,0,192.168.100.46,be:ff:34:42:10:01,be:ff:34,80,192.168.100.5,ae:bb:10:44:55:60,ae:bb:10,80,...,0,HTTP,Web,1,1,NaN,NaN,NaN,NaN,NaN
2,2,0,192.168.100.6,bb:aa:cc:98:55:43,bb:aa:cc,80,192.168.100.3,fa:cb:34:12:44:59,fa:cb:34,80,...,0,HTTP,Web,1,1,NaN,NaN,NaN,NaN,NaN
3,3,0,192.168.100.7,fa:cb:34:12:44:59,fa:cb:34,365,192.168.100.3,ba:ba:ca:6a:00:12,ba:ba:ca,565,...,0,Unknown,Unspecified,0,0,NaN,NaN,NaN,NaN,NaN
4,4,0,192.168.100.3,00:50:56:be:26:db,00:50:56,50850,13.54.166.67,00:50:56:be:b5:f6,00:50:56,8883,...,0,TLS,Web,0,6,NaN,NaN,NaN,NaN,NaN

In [10]:
# Cargar DataFrame N°8
df_to_label_08 = load_csv(r'CSVs/f/USACH/Ayudantias/Investigacion-Redes/PCAPs/Bot-IoT/Theft/Data_Exfiltration/IoT_Dataset_data_theft__00008_20180618111730.csv')
df_to_label_08.head(5)

,id,expiration_id,src_ip,src_mac,src_oui,src_port,dst_ip,dst_mac,dst_oui,dst_port,...,dst2src_fin_packets,application_name,application_category_name,application_is_guessed,application_confidence,requested_server_name,client_fingerprint,server_fingerprint,user_agent,content_type
0,0,0,192.168.100.46,be:ff:34:42:10:01,be:ff:34,80,192.168.100.5,ae:bb:10:44:55:60,ae:bb:10,80,...,0,HTTP,Web,1,1,NaN,NaN,NaN,NaN,NaN
1,1,0,192.168.100.7,fa:cb:34:12:44:59,fa:cb:34,365,192.168.100.3,ba:ba:ca:6a:00:12,ba:ba:ca,565,...,0,Unknown,Unspecified,0,0,NaN,NaN,NaN,NaN,NaN
2,2,0,192.168.100.6,00:50:56:be:4f:b7,00:50:56,49160,192.168.100.149,00:50:56:be:c0:38,00:50:56,4444,...,0,Unknown,Unspecified,0,0,NaN,NaN,NaN,NaN,NaN
3,3,0,192.168.100.3,00:50:56:be:26:db,00:50:56,50850,13.54.166.67,00:50:56:be:b5:f6,00:50:56,8883,...,0,TLS,Web,0,6,NaN,NaN,NaN,NaN,NaN
4,4,0,192.168.100.6,bb:aa:cc:98:55:43,bb:aa:cc,80,192.168.100.3,fa:cb:34:12:44:59,fa:cb:34,80,...,0,HTTP,Web,1,1,NaN,NaN,NaN,NaN,NaN

In [11]:
# Cargar DataFrame N°9
df_to_label_09 = load_csv(r'CSVs/f/USACH/Ayudantias/Investigacion-Redes/PCAPs/Bot-IoT/Theft/Data_Exfiltration/IoT_Dataset_data_theft__00009_20180618111838.csv')
df_to_label_09.head(5)

,id,expiration_id,src_ip,src_mac,src_oui,src_port,dst_ip,dst_mac,dst_oui,dst_port,...,dst2src_fin_packets,application_name,application_category_name,application_is_guessed,application_confidence,requested_server_name,client_fingerprint,server_fingerprint,user_agent,content_type
0,0,0,192.168.100.46,be:ff:34:42:10:01,be:ff:34,80,192.168.100.5,ae:bb:10:44:55:60,ae:bb:10,80,...,0,Unknown,Unspecified,0,0,NaN,NaN,NaN,NaN,NaN
1,1,0,192.168.100.6,bb:aa:cc:98:55:43,bb:aa:cc,80,192.168.100.3,fa:cb:34:12:44:59,fa:cb:34,80,...,0,HTTP,Web,1,1,NaN,NaN,NaN,NaN,NaN
2,2,0,192.168.100.149,00:50:56:be:c0:38,00:50:56,4444,192.168.100.6,00:50:56:be:4f:b7,00:50:56,49160,...,0,Unknown,Unspecified,0,0,NaN,NaN,NaN,NaN,NaN
3,3,0,192.168.100.46,be:ff:34:42:10:01,be:ff:34,80,192.168.100.5,ae:bb:10:44:55:60,ae:bb:10,80,...,0,HTTP,Web,1,1,NaN,NaN,NaN,NaN,NaN
4,4,0,192.168.100.7,fa:cb:34:12:44:59,fa:cb:34,365,192.168.100.3,ba:ba:ca:6a:00:12,ba:ba:ca,565,...,0,Unknown,Unspecified,0,0,NaN,NaN,NaN,NaN,NaN

In [12]:
# Cargar DataFrame N°10
df_to_label_10 = load_csv(r'CSVs/f/USACH/Ayudantias/Investigacion-Redes/PCAPs/Bot-IoT/Theft/Data_Exfiltration/IoT_Dataset_data_theft__00010_20180618112008.csv')
df_to_label_10.head(5)

,id,expiration_id,src_ip,src_mac,src_oui,src_port,dst_ip,dst_mac,dst_oui,dst_port,...,dst2src_fin_packets,application_name,application_category_name,application_is_guessed,application_confidence,requested_server_name,client_fingerprint,server_fingerprint,user_agent,content_type
0,0,0,192.168.100.3,fa:cb:34:12:44:59,fa:cb:34,80,192.168.100.55,ff:ea:24:21:12:13,ff:ea:24,8080,...,0,HTTP,Web,1,1,NaN,NaN,NaN,NaN,NaN
1,1,0,192.168.100.5,ae:bb:10:44:55:60,ae:bb:10,80,192.168.100.46,be:ff:34:42:10:01,be:ff:34,3456,...,0,Unknown,Unspecified,0,0,NaN,NaN,NaN,NaN,NaN
2,2,0,192.168.100.6,bb:aa:cc:98:55:43,bb:aa:cc,80,192.168.100.3,fa:cb:34:12:44:59,fa:cb:34,80,...,0,HTTP,Web,1,1,NaN,NaN,NaN,NaN,NaN
3,3,0,192.168.100.5,ae:bb:10:44:55:60,ae:bb:10,0,192.168.100.3,fa:cb:34:12:44:59,fa:cb:34,0,...,0,Unknown,Unspecified,0,0,NaN,NaN,NaN,NaN,NaN
4,4,0,192.168.100.150,00:50:56:be:02:54,00:50:56,4433,192.168.100.3,00:50:56:be:26:db,00:50:56,50032,...,0,Unknown,Unspecified,0,0,NaN,NaN,NaN,NaN,NaN

In [13]:
# Cargar DataFrame N°11
df_to_label_11 = load_csv(r'CSVs/f/USACH/Ayudantias/Investigacion-Redes/PCAPs/Bot-IoT/Theft/Data_Exfiltration/IoT_Dataset_data_theft__00011_20180618112146.csv')
df_to_label_11.head(5)

,id,expiration_id,src_ip,src_mac,src_oui,src_port,dst_ip,dst_mac,dst_oui,dst_port,...,dst2src_fin_packets,application_name,application_category_name,application_is_guessed,application_confidence,requested_server_name,client_fingerprint,server_fingerprint,user_agent,content_type
0,0,0,192.168.100.46,be:ff:34:42:10:01,be:ff:34,80,192.168.100.5,ae:bb:10:44:55:60,ae:bb:10,80,...,0,Unknown,Unspecified,0,0,NaN,NaN,NaN,NaN,NaN
1,1,0,192.168.100.6,00:50:56:be:4f:b7,00:50:56,138,192.168.100.255,ff:ff:ff:ff:ff:ff,ff:ff:ff,138,...,0,NetBIOS.SMBv1,System,0,6,wininst,NaN,NaN,NaN,NaN
2,2,0,192.168.100.46,be:ff:34:42:10:01,be:ff:34,80,192.168.100.5,ae:bb:10:44:55:60,ae:bb:10,80,...,0,HTTP,Web,1,1,NaN,NaN,NaN,NaN,NaN
3,3,0,192.168.100.7,fa:cb:34:12:44:59,fa:cb:34,365,192.168.100.3,ba:ba:ca:6a:00:12,ba:ba:ca,565,...,0,Unknown,Unspecified,0,0,NaN,NaN,NaN,NaN,NaN
4,4,0,192.168.100.3,00:50:56:be:26:db,00:50:56,50850,13.54.166.67,00:50:56:be:b5:f6,00:50:56,8883,...,0,TLS,Web,0,6,NaN,NaN,NaN,NaN,NaN

In [14]:
# Cargar DataFrame N°12
df_to_label_12 = load_csv(r'CSVs/f/USACH/Ayudantias/Investigacion-Redes/PCAPs/Bot-IoT/Theft/Data_Exfiltration/IoT_Dataset_data_theft__00012_20180618112555.csv')
df_to_label_12.head(5)

,id,expiration_id,src_ip,src_mac,src_oui,src_port,dst_ip,dst_mac,dst_oui,dst_port,...,dst2src_fin_packets,application_name,application_category_name,application_is_guessed,application_confidence,requested_server_name,client_fingerprint,server_fingerprint,user_agent,content_type
0,0,0,192.168.100.6,bb:aa:cc:98:55:43,bb:aa:cc,80,192.168.100.3,fa:cb:34:12:44:59,fa:cb:34,80,...,0,HTTP,Web,1,1,NaN,NaN,NaN,NaN,NaN
1,1,0,192.168.100.46,be:ff:34:42:10:01,be:ff:34,3456,192.168.100.5,ae:bb:10:44:55:60,ae:bb:10,80,...,0,Unknown,Unspecified,0,0,NaN,NaN,NaN,NaN,NaN
2,2,0,192.168.100.149,00:50:56:be:c0:38,00:50:56,4444,192.168.100.6,00:50:56:be:4f:b7,00:50:56,49160,...,0,Unknown,Unspecified,0,0,NaN,NaN,NaN,NaN,NaN
3,3,0,192.168.100.46,be:ff:34:42:10:01,be:ff:34,80,192.168.100.5,ae:bb:10:44:55:60,ae:bb:10,80,...,0,HTTP,Web,1,1,NaN,NaN,NaN,NaN,NaN
4,4,0,192.168.100.55,ff:ea:24:21:12:13,ff:ea:24,8080,192.168.100.3,fa:cb:34:12:44:59,fa:cb:34,80,...,0,HTTP,Web,1,1,NaN,NaN,NaN,NaN,NaN

In [15]:
# Cargar DataFrame N°13
df_to_label_13 = load_csv(r'CSVs/f/USACH/Ayudantias/Investigacion-Redes/PCAPs/Bot-IoT/Theft/Data_Exfiltration/IoT_Dataset_data_theft__00013_20180618112736.csv')
df_to_label_13.head(5)

,id,expiration_id,src_ip,src_mac,src_oui,src_port,dst_ip,dst_mac,dst_oui,dst_port,...,dst2src_fin_packets,application_name,application_category_name,application_is_guessed,application_confidence,requested_server_name,client_fingerprint,server_fingerprint,user_agent,content_type
0,0,0,192.168.100.46,be:ff:34:42:10:01,be:ff:34,80,192.168.100.5,ae:bb:10:44:55:60,ae:bb:10,80,...,0,Unknown,Unspecified,0,0,NaN,NaN,NaN,NaN,NaN
1,1,0,192.168.100.46,be:ff:34:42:10:01,be:ff:34,3456,192.168.100.5,ae:bb:10:44:55:60,ae:bb:10,80,...,0,Unknown,Unspecified,0,0,NaN,NaN,NaN,NaN,NaN
2,2,0,192.168.100.55,ff:ea:24:21:12:13,ff:ea:24,8080,192.168.100.3,fa:cb:34:12:44:59,fa:cb:34,80,...,0,HTTP,Web,1,1,NaN,NaN,NaN,NaN,NaN
3,3,0,192.168.100.5,ae:bb:10:44:55:60,ae:bb:10,0,192.168.100.3,fa:cb:34:12:44:59,fa:cb:34,0,...,0,Unknown,Unspecified,0,0,NaN,NaN,NaN,NaN,NaN
4,4,0,192.168.100.150,00:50:56:be:02:54,00:50:56,4433,192.168.100.3,00:50:56:be:26:db,00:50:56,50032,...,0,Unknown,Unspecified,0,0,NaN,NaN,NaN,NaN,NaN

### Cargar DataFrame de Referencia

In [16]:
# Cargar DataFrame de referencia
reference_df = load_csv(r'CSVs/Labeling/Bot-IoT/Data_exfiltration.csv')
reference_df.head(5)

,stime,flgs,proto,saddr,sport,dir,daddr,dport,pkts,bytes,...,dpkts,sbytes,dbytes,rate,srate,drate,record,attack,category,subcategory
0,1.529284e+09,e,udp,192.168.100.6,138.0,->,192.168.100.255,138.0,4,986,...,0,986,0,0.002777,0.002777,0.000000,,0,Normal,Normal
1,1.529284e+09,e,tcp,192.168.100.3,60864.0,<?>,172.217.25.138,443.0,12,1053,...,4,697,356,0.098173,0.062473,0.026774,,0,Normal,Normal
2,1.529284e+09,e,udp,192.168.100.7,138.0,->,192.168.100.255,138.0,4,1086,...,0,1086,0,0.004102,0.004102,0.000000,,0,Normal,Normal
3,1.529284e+09,e,arp,192.168.100.149,NaN,who,192.168.100.6,NaN,26,1560,...,13,780,780,0.021496,0.010318,0.010318,,1,Theft,Data_Exfiltration
4,1.529284e+09,e,tcp,192.168.100.150,36682.0,->,192.168.100.3,22.0,28,5098,...,15,1640,3458,55.147282,24.509903,28.594887,,1,Theft,Data_Exfiltration

## Procesar DataFrames

### Data Theft N°1

In [17]:
# Procesar etiquetado de DataFrames
tagged_df_01 = process_tagging(reference_df, df_to_label_01, "Bot-IoT", config)
tagged_df_01

2024-12-22 13:35:13 - csv_processor - INFO - Iniciando proceso de etiquetado...
2024-12-22 13:35:13 - csv_processor - INFO - Iniciando el proceso de etiquetado...
2024-12-22 13:35:13 - csv_processor - INFO - Operando los DataFrames...
2024-12-22 13:35:13 - csv_processor - INFO - Proceso de etiquetado completado.

,id,expiration_id,src_ip,src_mac,src_oui,src_port,dst_ip,dst_mac,dst_oui,dst_port,...,application_is_guessed,application_confidence,requested_server_name,client_fingerprint,server_fingerprint,user_agent,content_type,attack,category,subcategory
0,2,0,1921681003,00:50:56:be:26:db,00:50:56,60864,17221725138,00:50:56:be:b5:f6,00:50:56,443,...,0,6,NaN,NaN,NaN,NaN,NaN,0,Normal,Normal
1,6,0,192168100150,00:50:56:be:02:54,00:50:56,36682,1921681003,00:50:56:be:26:db,00:50:56,22,...,0,6,NaN,905CE75BA9C8343782F8D76D938F5CE8,D41D8CD98F00B204E9800998ECF8427E,NaN,NaN,1,Theft,Data_Exfiltration
2,7,0,192168100150,00:50:56:be:02:54,00:50:56,36686,1921681003,00:50:56:be:26:db,00:50:56,22,...,0,6,NaN,905CE75BA9C8343782F8D76D938F5CE8,D41D8CD98F00B204E9800998ECF8427E,NaN,NaN,1,Theft,Data_Exfiltration
3,8,0,192168100150,00:50:56:be:02:54,00:50:56,36692,1921681003,00:50:56:be:26:db,00:50:56,22,...,0,6,NaN,905CE75BA9C8343782F8D76D938F5CE8,D41D8CD98F00B204E9800998ECF8427E,NaN,NaN,1,Theft,Data_Exfiltration
4,9,0,192168100150,00:50:56:be:02:54,00:50:56,36702,1921681003,00:50:56:be:26:db,00:50:56,22,...,0,6,NaN,905CE75BA9C8343782F8D76D938F5CE8,D41D8CD98F00B204E9800998ECF8427E,NaN,NaN,1,Theft,Data_Exfiltration
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,119,0,192168100150,00:50:56:be:02:54,00:50:56,36864,1921681003,00:50:56:be:26:db,00:50:56,22,...,0,6,NaN,905CE75BA9C8343782F8D76D938F5CE8,D41D8CD98F00B204E9800998ECF8427E,NaN,NaN,1,Theft,Data_Exfiltration
109,120,0,192168100150,00:50:56:be:02:54,00:50:56,36874,1921681003,00:50:56:be:26:db,00:50:56,22,...,0,6,NaN,905CE75BA9C8343782F8D76D938F5CE8,D41D8CD98F00B204E9800998ECF8427E,NaN,NaN,1,Theft,Data_Exfiltration
110,121,0,192168100150,00:50:56:be:02:54,00:50:56,36888,1921681003,00:50:56:be:26:db,00:50:56,22,...,0,6,NaN,905CE75BA9C8343782F8D76D938F5CE8,D41D8CD98F00B204E9800998ECF8427E,NaN,NaN,1,Theft,Data_Exfiltration
111,123,0,192168100150,00:50:56:be:02:54,00:50:56,36884,1921681003,00:50:56:be:26:db,00:50:56,22,...,0,6,NaN,NaN,NaN,NaN,NaN,1,Theft,Data_Exfiltration
112,124,0,192168100150,00:50:56:be:02:54,00:50:56,36894,1921681003,00:50:56:be:26:db,00:50:56,22,...,0,6,NaN,905CE75BA9C8343782F8D76D938F5CE8,D41D8CD98F00B204E9800998ECF8427E,NaN,NaN,1,Theft,Data_Exfiltration

In [18]:
label_counts_01 = analyze_labels_in_dataframe(tagged_df_01)
print("Resultados del análisis del DataFrame:")
for column, counts in label_counts_01.items():
    print(f"Column: {column}")
    for label, count in counts.items():
        print(f"  {label}: {count}")

Resultados del análisis del DataFrame:
Column: attack
  1: 110
  0: 3
Column: category
  Theft: 110
  Normal: 3
Column: subcategory
  Data_Exfiltration: 110
  Normal: 3

### Data Theft N°2

In [19]:
# Procesar etiquetado de DataFrames
tagged_df_02 = process_tagging(reference_df, df_to_label_02, "Bot-IoT", config)
tagged_df_02.head(5)

2024-12-22 13:35:14 - csv_processor - INFO - Iniciando proceso de etiquetado...
2024-12-22 13:35:14 - csv_processor - INFO - Iniciando el proceso de etiquetado...
2024-12-22 13:35:14 - csv_processor - INFO - Operando los DataFrames...
2024-12-22 13:35:14 - csv_processor - INFO - Proceso de etiquetado completado.

Empty DataFrame
Columns: [id, expiration_id, src_ip, src_mac, src_oui, src_port, dst_ip, dst_mac, dst_oui, dst_port, protocol, ip_version, vlan_id, tunnel_id, bidirectional_first_seen_ms, bidirectional_last_seen_ms, bidirectional_duration_ms, bidirectional_packets, bidirectional_bytes, src2dst_first_seen_ms, src2dst_last_seen_ms, src2dst_duration_ms, src2dst_packets, src2dst_bytes, dst2src_first_seen_ms, dst2src_last_seen_ms, dst2src_duration_ms, dst2src_packets, dst2src_bytes, bidirectional_min_ps, bidirectional_mean_ps, bidirectional_stddev_ps, bidirectional_max_ps, src2dst_min_ps, src2dst_mean_ps, src2dst_stddev_ps, src2dst_max_ps, dst2src_min_ps, dst2src_mean_ps, dst2src_stddev_ps, dst2src_max_ps, bidirectional_min_piat_ms, bidirectional_mean_piat_ms, bidirectional_stddev_piat_ms, bidirectional_max_piat_ms, src2dst_min_piat_ms, src2dst_mean_piat_ms, src2dst_stddev_piat_ms, src2dst_max_piat_ms, dst2src_min_piat_ms, dst2src_mean_piat_ms, dst2src_stddev_piat_ms, dst2src_max_piat_ms, bidirectional_syn_packets, bidirectional_cwr_packets, bidirectional_ece_packets, bidirectional_urg_packets, bidirectional_ack_packets, bidirectional_psh_packets, bidirectional_rst_packets, bidirectional_fin_packets, src2dst_syn_packets, src2dst_cwr_packets, src2dst_ece_packets, src2dst_urg_packets, src2dst_ack_packets, src2dst_psh_packets, src2dst_rst_packets, src2dst_fin_packets, dst2src_syn_packets, dst2src_cwr_packets, dst2src_ece_packets, dst2src_urg_packets, dst2src_ack_packets, dst2src_psh_packets, dst2src_rst_packets, dst2src_fin_packets, application_name, application_category_name, application_is_guessed, application_confidence, requested_server_name, client_fingerprint, server_fingerprint, user_agent, content_type, attack, category, subcategory]
Index: []

[0 rows x 89 columns]

In [20]:
label_counts_02 = analyze_labels_in_dataframe(tagged_df_02)
print("Resultados del análisis del DataFrame:")
for column, counts in label_counts_02.items():
    print(f"Column: {column}")
    for label, count in counts.items():
        print(f"  {label}: {count}")

Resultados del análisis del DataFrame:
Column: attack
Column: category
Column: subcategory

### Data Theft N°3

In [21]:
# Procesar etiquetado de DataFrames
tagged_df_03 = process_tagging(reference_df, df_to_label_03, "Bot-IoT", config)
tagged_df_03.head(5)

2024-12-22 13:35:14 - csv_processor - INFO - Iniciando proceso de etiquetado...
2024-12-22 13:35:14 - csv_processor - INFO - Iniciando el proceso de etiquetado...
2024-12-22 13:35:14 - csv_processor - INFO - Operando los DataFrames...
2024-12-22 13:35:14 - csv_processor - INFO - Proceso de etiquetado completado.

Empty DataFrame
Columns: [id, expiration_id, src_ip, src_mac, src_oui, src_port, dst_ip, dst_mac, dst_oui, dst_port, protocol, ip_version, vlan_id, tunnel_id, bidirectional_first_seen_ms, bidirectional_last_seen_ms, bidirectional_duration_ms, bidirectional_packets, bidirectional_bytes, src2dst_first_seen_ms, src2dst_last_seen_ms, src2dst_duration_ms, src2dst_packets, src2dst_bytes, dst2src_first_seen_ms, dst2src_last_seen_ms, dst2src_duration_ms, dst2src_packets, dst2src_bytes, bidirectional_min_ps, bidirectional_mean_ps, bidirectional_stddev_ps, bidirectional_max_ps, src2dst_min_ps, src2dst_mean_ps, src2dst_stddev_ps, src2dst_max_ps, dst2src_min_ps, dst2src_mean_ps, dst2src_stddev_ps, dst2src_max_ps, bidirectional_min_piat_ms, bidirectional_mean_piat_ms, bidirectional_stddev_piat_ms, bidirectional_max_piat_ms, src2dst_min_piat_ms, src2dst_mean_piat_ms, src2dst_stddev_piat_ms, src2dst_max_piat_ms, dst2src_min_piat_ms, dst2src_mean_piat_ms, dst2src_stddev_piat_ms, dst2src_max_piat_ms, bidirectional_syn_packets, bidirectional_cwr_packets, bidirectional_ece_packets, bidirectional_urg_packets, bidirectional_ack_packets, bidirectional_psh_packets, bidirectional_rst_packets, bidirectional_fin_packets, src2dst_syn_packets, src2dst_cwr_packets, src2dst_ece_packets, src2dst_urg_packets, src2dst_ack_packets, src2dst_psh_packets, src2dst_rst_packets, src2dst_fin_packets, dst2src_syn_packets, dst2src_cwr_packets, dst2src_ece_packets, dst2src_urg_packets, dst2src_ack_packets, dst2src_psh_packets, dst2src_rst_packets, dst2src_fin_packets, application_name, application_category_name, application_is_guessed, application_confidence, requested_server_name, client_fingerprint, server_fingerprint, user_agent, content_type, attack, category, subcategory]
Index: []

[0 rows x 89 columns]

In [22]:
label_counts_03 = analyze_labels_in_dataframe(tagged_df_03)
print("Resultados del análisis del DataFrame:")
for column, counts in label_counts_03.items():
    print(f"Column: {column}")
    for label, count in counts.items():
        print(f"  {label}: {count}")

Resultados del análisis del DataFrame:
Column: attack
Column: category
Column: subcategory

### Data Theft N°4

In [23]:
# Procesar etiquetado de DataFrames
tagged_df_04 = process_tagging(reference_df, df_to_label_04, "Bot-IoT", config)
tagged_df_04.head(5)

2024-12-22 13:35:14 - csv_processor - INFO - Iniciando proceso de etiquetado...
2024-12-22 13:35:14 - csv_processor - INFO - Iniciando el proceso de etiquetado...
2024-12-22 13:35:14 - csv_processor - INFO - Operando los DataFrames...
2024-12-22 13:35:14 - csv_processor - INFO - Proceso de etiquetado completado.

Empty DataFrame
Columns: [id, expiration_id, src_ip, src_mac, src_oui, src_port, dst_ip, dst_mac, dst_oui, dst_port, protocol, ip_version, vlan_id, tunnel_id, bidirectional_first_seen_ms, bidirectional_last_seen_ms, bidirectional_duration_ms, bidirectional_packets, bidirectional_bytes, src2dst_first_seen_ms, src2dst_last_seen_ms, src2dst_duration_ms, src2dst_packets, src2dst_bytes, dst2src_first_seen_ms, dst2src_last_seen_ms, dst2src_duration_ms, dst2src_packets, dst2src_bytes, bidirectional_min_ps, bidirectional_mean_ps, bidirectional_stddev_ps, bidirectional_max_ps, src2dst_min_ps, src2dst_mean_ps, src2dst_stddev_ps, src2dst_max_ps, dst2src_min_ps, dst2src_mean_ps, dst2src_stddev_ps, dst2src_max_ps, bidirectional_min_piat_ms, bidirectional_mean_piat_ms, bidirectional_stddev_piat_ms, bidirectional_max_piat_ms, src2dst_min_piat_ms, src2dst_mean_piat_ms, src2dst_stddev_piat_ms, src2dst_max_piat_ms, dst2src_min_piat_ms, dst2src_mean_piat_ms, dst2src_stddev_piat_ms, dst2src_max_piat_ms, bidirectional_syn_packets, bidirectional_cwr_packets, bidirectional_ece_packets, bidirectional_urg_packets, bidirectional_ack_packets, bidirectional_psh_packets, bidirectional_rst_packets, bidirectional_fin_packets, src2dst_syn_packets, src2dst_cwr_packets, src2dst_ece_packets, src2dst_urg_packets, src2dst_ack_packets, src2dst_psh_packets, src2dst_rst_packets, src2dst_fin_packets, dst2src_syn_packets, dst2src_cwr_packets, dst2src_ece_packets, dst2src_urg_packets, dst2src_ack_packets, dst2src_psh_packets, dst2src_rst_packets, dst2src_fin_packets, application_name, application_category_name, application_is_guessed, application_confidence, requested_server_name, client_fingerprint, server_fingerprint, user_agent, content_type, attack, category, subcategory]
Index: []

[0 rows x 89 columns]

In [24]:
label_counts_04 = analyze_labels_in_dataframe(tagged_df_04)
print("Resultados del análisis del DataFrame:")
for column, counts in label_counts_04.items():
    print(f"Column: {column}")
    for label, count in counts.items():
        print(f"  {label}: {count}")

Resultados del análisis del DataFrame:
Column: attack
Column: category
Column: subcategory

### Data Theft N°5

In [25]:
# Procesar etiquetado de DataFrames
tagged_df_05 = process_tagging(reference_df, df_to_label_05, "Bot-IoT", config)
tagged_df_05.head(5)

2024-12-22 13:35:14 - csv_processor - INFO - Iniciando proceso de etiquetado...
2024-12-22 13:35:14 - csv_processor - INFO - Iniciando el proceso de etiquetado...
2024-12-22 13:35:14 - csv_processor - INFO - Operando los DataFrames...
2024-12-22 13:35:14 - csv_processor - INFO - Proceso de etiquetado completado.

,id,expiration_id,src_ip,src_mac,src_oui,src_port,dst_ip,dst_mac,dst_oui,dst_port,...,application_is_guessed,application_confidence,requested_server_name,client_fingerprint,server_fingerprint,user_agent,content_type,attack,category,subcategory
0,6,0,1921681006,00:50:56:be:4f:b7,00:50:56,52670,1921681001,00:50:56:be:b5:f6,00:50:56,53,...,0,6,teredo.ipv6.microsoft.com,NaN,NaN,NaN,NaN,0,Normal,Normal

In [26]:
label_counts_05 = analyze_labels_in_dataframe(tagged_df_05)
print("Resultados del análisis del DataFrame:")
for column, counts in label_counts_05.items():
    print(f"Column: {column}")
    for label, count in counts.items():
        print(f"  {label}: {count}")

Resultados del análisis del DataFrame:
Column: attack
  0: 1
Column: category
  Normal: 1
Column: subcategory
  Normal: 1

### Data Theft N°6

In [27]:
# Procesar etiquetado de DataFrames
tagged_df_06 = process_tagging(reference_df, df_to_label_06, "Bot-IoT", config)
tagged_df_06.head(5)

2024-12-22 13:35:14 - csv_processor - INFO - Iniciando proceso de etiquetado...
2024-12-22 13:35:14 - csv_processor - INFO - Iniciando el proceso de etiquetado...
2024-12-22 13:35:14 - csv_processor - INFO - Operando los DataFrames...
2024-12-22 13:35:14 - csv_processor - INFO - Proceso de etiquetado completado.

Empty DataFrame
Columns: [id, expiration_id, src_ip, src_mac, src_oui, src_port, dst_ip, dst_mac, dst_oui, dst_port, protocol, ip_version, vlan_id, tunnel_id, bidirectional_first_seen_ms, bidirectional_last_seen_ms, bidirectional_duration_ms, bidirectional_packets, bidirectional_bytes, src2dst_first_seen_ms, src2dst_last_seen_ms, src2dst_duration_ms, src2dst_packets, src2dst_bytes, dst2src_first_seen_ms, dst2src_last_seen_ms, dst2src_duration_ms, dst2src_packets, dst2src_bytes, bidirectional_min_ps, bidirectional_mean_ps, bidirectional_stddev_ps, bidirectional_max_ps, src2dst_min_ps, src2dst_mean_ps, src2dst_stddev_ps, src2dst_max_ps, dst2src_min_ps, dst2src_mean_ps, dst2src_stddev_ps, dst2src_max_ps, bidirectional_min_piat_ms, bidirectional_mean_piat_ms, bidirectional_stddev_piat_ms, bidirectional_max_piat_ms, src2dst_min_piat_ms, src2dst_mean_piat_ms, src2dst_stddev_piat_ms, src2dst_max_piat_ms, dst2src_min_piat_ms, dst2src_mean_piat_ms, dst2src_stddev_piat_ms, dst2src_max_piat_ms, bidirectional_syn_packets, bidirectional_cwr_packets, bidirectional_ece_packets, bidirectional_urg_packets, bidirectional_ack_packets, bidirectional_psh_packets, bidirectional_rst_packets, bidirectional_fin_packets, src2dst_syn_packets, src2dst_cwr_packets, src2dst_ece_packets, src2dst_urg_packets, src2dst_ack_packets, src2dst_psh_packets, src2dst_rst_packets, src2dst_fin_packets, dst2src_syn_packets, dst2src_cwr_packets, dst2src_ece_packets, dst2src_urg_packets, dst2src_ack_packets, dst2src_psh_packets, dst2src_rst_packets, dst2src_fin_packets, application_name, application_category_name, application_is_guessed, application_confidence, requested_server_name, client_fingerprint, server_fingerprint, user_agent, content_type, attack, category, subcategory]
Index: []

[0 rows x 89 columns]

In [28]:
label_counts_06 = analyze_labels_in_dataframe(tagged_df_06)
print("Resultados del análisis del DataFrame:")
for column, counts in label_counts_06.items():
    print(f"Column: {column}")
    for label, count in counts.items():
        print(f"  {label}: {count}")

Resultados del análisis del DataFrame:
Column: attack
Column: category
Column: subcategory

### Data Theft N°7

In [29]:
# Procesar etiquetado de DataFrames
tagged_df_07 = process_tagging(reference_df, df_to_label_07, "Bot-IoT", config)
tagged_df_07.head(5)

2024-12-22 13:35:14 - csv_processor - INFO - Iniciando proceso de etiquetado...
2024-12-22 13:35:14 - csv_processor - INFO - Iniciando el proceso de etiquetado...
2024-12-22 13:35:14 - csv_processor - INFO - Operando los DataFrames...
2024-12-22 13:35:14 - csv_processor - INFO - Proceso de etiquetado completado.

Empty DataFrame
Columns: [id, expiration_id, src_ip, src_mac, src_oui, src_port, dst_ip, dst_mac, dst_oui, dst_port, protocol, ip_version, vlan_id, tunnel_id, bidirectional_first_seen_ms, bidirectional_last_seen_ms, bidirectional_duration_ms, bidirectional_packets, bidirectional_bytes, src2dst_first_seen_ms, src2dst_last_seen_ms, src2dst_duration_ms, src2dst_packets, src2dst_bytes, dst2src_first_seen_ms, dst2src_last_seen_ms, dst2src_duration_ms, dst2src_packets, dst2src_bytes, bidirectional_min_ps, bidirectional_mean_ps, bidirectional_stddev_ps, bidirectional_max_ps, src2dst_min_ps, src2dst_mean_ps, src2dst_stddev_ps, src2dst_max_ps, dst2src_min_ps, dst2src_mean_ps, dst2src_stddev_ps, dst2src_max_ps, bidirectional_min_piat_ms, bidirectional_mean_piat_ms, bidirectional_stddev_piat_ms, bidirectional_max_piat_ms, src2dst_min_piat_ms, src2dst_mean_piat_ms, src2dst_stddev_piat_ms, src2dst_max_piat_ms, dst2src_min_piat_ms, dst2src_mean_piat_ms, dst2src_stddev_piat_ms, dst2src_max_piat_ms, bidirectional_syn_packets, bidirectional_cwr_packets, bidirectional_ece_packets, bidirectional_urg_packets, bidirectional_ack_packets, bidirectional_psh_packets, bidirectional_rst_packets, bidirectional_fin_packets, src2dst_syn_packets, src2dst_cwr_packets, src2dst_ece_packets, src2dst_urg_packets, src2dst_ack_packets, src2dst_psh_packets, src2dst_rst_packets, src2dst_fin_packets, dst2src_syn_packets, dst2src_cwr_packets, dst2src_ece_packets, dst2src_urg_packets, dst2src_ack_packets, dst2src_psh_packets, dst2src_rst_packets, dst2src_fin_packets, application_name, application_category_name, application_is_guessed, application_confidence, requested_server_name, client_fingerprint, server_fingerprint, user_agent, content_type, attack, category, subcategory]
Index: []

[0 rows x 89 columns]

In [30]:
label_counts_07 = analyze_labels_in_dataframe(tagged_df_07)
print("Resultados del análisis del DataFrame:")
for column, counts in label_counts_07.items():
    print(f"Column: {column}")
    for label, count in counts.items():
        print(f"  {label}: {count}")

Resultados del análisis del DataFrame:
Column: attack
Column: category
Column: subcategory

### Data Theft N°8

In [31]:
# Procesar etiquetado de DataFrames
tagged_df_08 = process_tagging(reference_df, df_to_label_08, "Bot-IoT", config)
tagged_df_08.head(5)

2024-12-22 13:35:15 - csv_processor - INFO - Iniciando proceso de etiquetado...
2024-12-22 13:35:15 - csv_processor - INFO - Iniciando el proceso de etiquetado...
2024-12-22 13:35:15 - csv_processor - INFO - Operando los DataFrames...
2024-12-22 13:35:15 - csv_processor - INFO - Proceso de etiquetado completado.

Empty DataFrame
Columns: [id, expiration_id, src_ip, src_mac, src_oui, src_port, dst_ip, dst_mac, dst_oui, dst_port, protocol, ip_version, vlan_id, tunnel_id, bidirectional_first_seen_ms, bidirectional_last_seen_ms, bidirectional_duration_ms, bidirectional_packets, bidirectional_bytes, src2dst_first_seen_ms, src2dst_last_seen_ms, src2dst_duration_ms, src2dst_packets, src2dst_bytes, dst2src_first_seen_ms, dst2src_last_seen_ms, dst2src_duration_ms, dst2src_packets, dst2src_bytes, bidirectional_min_ps, bidirectional_mean_ps, bidirectional_stddev_ps, bidirectional_max_ps, src2dst_min_ps, src2dst_mean_ps, src2dst_stddev_ps, src2dst_max_ps, dst2src_min_ps, dst2src_mean_ps, dst2src_stddev_ps, dst2src_max_ps, bidirectional_min_piat_ms, bidirectional_mean_piat_ms, bidirectional_stddev_piat_ms, bidirectional_max_piat_ms, src2dst_min_piat_ms, src2dst_mean_piat_ms, src2dst_stddev_piat_ms, src2dst_max_piat_ms, dst2src_min_piat_ms, dst2src_mean_piat_ms, dst2src_stddev_piat_ms, dst2src_max_piat_ms, bidirectional_syn_packets, bidirectional_cwr_packets, bidirectional_ece_packets, bidirectional_urg_packets, bidirectional_ack_packets, bidirectional_psh_packets, bidirectional_rst_packets, bidirectional_fin_packets, src2dst_syn_packets, src2dst_cwr_packets, src2dst_ece_packets, src2dst_urg_packets, src2dst_ack_packets, src2dst_psh_packets, src2dst_rst_packets, src2dst_fin_packets, dst2src_syn_packets, dst2src_cwr_packets, dst2src_ece_packets, dst2src_urg_packets, dst2src_ack_packets, dst2src_psh_packets, dst2src_rst_packets, dst2src_fin_packets, application_name, application_category_name, application_is_guessed, application_confidence, requested_server_name, client_fingerprint, server_fingerprint, user_agent, content_type, attack, category, subcategory]
Index: []

[0 rows x 89 columns]

In [32]:
label_counts_08 = analyze_labels_in_dataframe(tagged_df_08)
print("Resultados del análisis del DataFrame:")
for column, counts in label_counts_08.items():
    print(f"Column: {column}")
    for label, count in counts.items():
        print(f"  {label}: {count}")

Resultados del análisis del DataFrame:
Column: attack
Column: category
Column: subcategory

### Data Theft N°9

In [33]:
# Procesar etiquetado de DataFrames
tagged_df_09 = process_tagging(reference_df, df_to_label_09, "Bot-IoT", config)
tagged_df_09.head(5)

2024-12-22 13:35:15 - csv_processor - INFO - Iniciando proceso de etiquetado...
2024-12-22 13:35:15 - csv_processor - INFO - Iniciando el proceso de etiquetado...
2024-12-22 13:35:15 - csv_processor - INFO - Operando los DataFrames...
2024-12-22 13:35:15 - csv_processor - INFO - Proceso de etiquetado completado.

,id,expiration_id,src_ip,src_mac,src_oui,src_port,dst_ip,dst_mac,dst_oui,dst_port,...,application_is_guessed,application_confidence,requested_server_name,client_fingerprint,server_fingerprint,user_agent,content_type,attack,category,subcategory
0,6,0,192168100150,00:50:56:be:02:54,00:50:56,49421,27124125251,00:50:56:be:b5:f6,00:50:56,123,...,0,6,NaN,NaN,NaN,NaN,NaN,0,Normal,Normal
1,7,0,1921681004,00:50:56:be:dd:cc,00:50:56,49844,91189944,00:50:56:be:b5:f6,00:50:56,123,...,0,6,NaN,NaN,NaN,NaN,NaN,0,Normal,Normal

In [34]:
label_counts_09 = analyze_labels_in_dataframe(tagged_df_09)
print("Resultados del análisis del DataFrame:")
for column, counts in label_counts_09.items():
    print(f"Column: {column}")
    for label, count in counts.items():
        print(f"  {label}: {count}")

Resultados del análisis del DataFrame:
Column: attack
  0: 2
Column: category
  Normal: 2
Column: subcategory
  Normal: 2

### Data Theft N°10

In [35]:
# Procesar etiquetado de DataFrames
tagged_df_10 = process_tagging(reference_df, df_to_label_10, "Bot-IoT", config)
tagged_df_10.head(5)

2024-12-22 13:35:15 - csv_processor - INFO - Iniciando proceso de etiquetado...
2024-12-22 13:35:15 - csv_processor - INFO - Iniciando el proceso de etiquetado...
2024-12-22 13:35:15 - csv_processor - INFO - Operando los DataFrames...
2024-12-22 13:35:15 - csv_processor - INFO - Proceso de etiquetado completado.

,id,expiration_id,src_ip,src_mac,src_oui,src_port,dst_ip,dst_mac,dst_oui,dst_port,...,application_is_guessed,application_confidence,requested_server_name,client_fingerprint,server_fingerprint,user_agent,content_type,attack,category,subcategory
0,1,0,1921681005,ae:bb:10:44:55:60,ae:bb:10,80,19216810046,be:ff:34:42:10:01,be:ff:34,3456,...,0,0,NaN,NaN,NaN,NaN,NaN,0,Normal,Normal

In [36]:
label_counts_10 = analyze_labels_in_dataframe(tagged_df_10)
print("Resultados del análisis del DataFrame:")
for column, counts in label_counts_10.items():
    print(f"Column: {column}")
    for label, count in counts.items():
        print(f"  {label}: {count}")

Resultados del análisis del DataFrame:
Column: attack
  0: 1
Column: category
  Normal: 1
Column: subcategory
  Normal: 1

### Data Theft N°11

In [37]:
# Procesar etiquetado de DataFrames
tagged_df_11 = process_tagging(reference_df, df_to_label_11, "Bot-IoT", config)
tagged_df_11.head(5)

2024-12-22 13:35:15 - csv_processor - INFO - Iniciando proceso de etiquetado...
2024-12-22 13:35:15 - csv_processor - INFO - Iniciando el proceso de etiquetado...
2024-12-22 13:35:15 - csv_processor - INFO - Operando los DataFrames...
2024-12-22 13:35:15 - csv_processor - INFO - Proceso de etiquetado completado.

Empty DataFrame
Columns: [id, expiration_id, src_ip, src_mac, src_oui, src_port, dst_ip, dst_mac, dst_oui, dst_port, protocol, ip_version, vlan_id, tunnel_id, bidirectional_first_seen_ms, bidirectional_last_seen_ms, bidirectional_duration_ms, bidirectional_packets, bidirectional_bytes, src2dst_first_seen_ms, src2dst_last_seen_ms, src2dst_duration_ms, src2dst_packets, src2dst_bytes, dst2src_first_seen_ms, dst2src_last_seen_ms, dst2src_duration_ms, dst2src_packets, dst2src_bytes, bidirectional_min_ps, bidirectional_mean_ps, bidirectional_stddev_ps, bidirectional_max_ps, src2dst_min_ps, src2dst_mean_ps, src2dst_stddev_ps, src2dst_max_ps, dst2src_min_ps, dst2src_mean_ps, dst2src_stddev_ps, dst2src_max_ps, bidirectional_min_piat_ms, bidirectional_mean_piat_ms, bidirectional_stddev_piat_ms, bidirectional_max_piat_ms, src2dst_min_piat_ms, src2dst_mean_piat_ms, src2dst_stddev_piat_ms, src2dst_max_piat_ms, dst2src_min_piat_ms, dst2src_mean_piat_ms, dst2src_stddev_piat_ms, dst2src_max_piat_ms, bidirectional_syn_packets, bidirectional_cwr_packets, bidirectional_ece_packets, bidirectional_urg_packets, bidirectional_ack_packets, bidirectional_psh_packets, bidirectional_rst_packets, bidirectional_fin_packets, src2dst_syn_packets, src2dst_cwr_packets, src2dst_ece_packets, src2dst_urg_packets, src2dst_ack_packets, src2dst_psh_packets, src2dst_rst_packets, src2dst_fin_packets, dst2src_syn_packets, dst2src_cwr_packets, dst2src_ece_packets, dst2src_urg_packets, dst2src_ack_packets, dst2src_psh_packets, dst2src_rst_packets, dst2src_fin_packets, application_name, application_category_name, application_is_guessed, application_confidence, requested_server_name, client_fingerprint, server_fingerprint, user_agent, content_type, attack, category, subcategory]
Index: []

[0 rows x 89 columns]

In [38]:
label_counts_11 = analyze_labels_in_dataframe(tagged_df_11)
print("Resultados del análisis del DataFrame:")
for column, counts in label_counts_11.items():
    print(f"Column: {column}")
    for label, count in counts.items():
        print(f"  {label}: {count}")

Resultados del análisis del DataFrame:
Column: attack
Column: category
Column: subcategory

### Data Theft N°12

In [39]:
# Procesar etiquetado de DataFrames
tagged_df_12 = process_tagging(reference_df, df_to_label_12, "Bot-IoT", config)
tagged_df_12.head(5)

2024-12-22 13:35:15 - csv_processor - INFO - Iniciando proceso de etiquetado...
2024-12-22 13:35:15 - csv_processor - INFO - Iniciando el proceso de etiquetado...
2024-12-22 13:35:15 - csv_processor - INFO - Operando los DataFrames...
2024-12-22 13:35:15 - csv_processor - INFO - Proceso de etiquetado completado.

Empty DataFrame
Columns: [id, expiration_id, src_ip, src_mac, src_oui, src_port, dst_ip, dst_mac, dst_oui, dst_port, protocol, ip_version, vlan_id, tunnel_id, bidirectional_first_seen_ms, bidirectional_last_seen_ms, bidirectional_duration_ms, bidirectional_packets, bidirectional_bytes, src2dst_first_seen_ms, src2dst_last_seen_ms, src2dst_duration_ms, src2dst_packets, src2dst_bytes, dst2src_first_seen_ms, dst2src_last_seen_ms, dst2src_duration_ms, dst2src_packets, dst2src_bytes, bidirectional_min_ps, bidirectional_mean_ps, bidirectional_stddev_ps, bidirectional_max_ps, src2dst_min_ps, src2dst_mean_ps, src2dst_stddev_ps, src2dst_max_ps, dst2src_min_ps, dst2src_mean_ps, dst2src_stddev_ps, dst2src_max_ps, bidirectional_min_piat_ms, bidirectional_mean_piat_ms, bidirectional_stddev_piat_ms, bidirectional_max_piat_ms, src2dst_min_piat_ms, src2dst_mean_piat_ms, src2dst_stddev_piat_ms, src2dst_max_piat_ms, dst2src_min_piat_ms, dst2src_mean_piat_ms, dst2src_stddev_piat_ms, dst2src_max_piat_ms, bidirectional_syn_packets, bidirectional_cwr_packets, bidirectional_ece_packets, bidirectional_urg_packets, bidirectional_ack_packets, bidirectional_psh_packets, bidirectional_rst_packets, bidirectional_fin_packets, src2dst_syn_packets, src2dst_cwr_packets, src2dst_ece_packets, src2dst_urg_packets, src2dst_ack_packets, src2dst_psh_packets, src2dst_rst_packets, src2dst_fin_packets, dst2src_syn_packets, dst2src_cwr_packets, dst2src_ece_packets, dst2src_urg_packets, dst2src_ack_packets, dst2src_psh_packets, dst2src_rst_packets, dst2src_fin_packets, application_name, application_category_name, application_is_guessed, application_confidence, requested_server_name, client_fingerprint, server_fingerprint, user_agent, content_type, attack, category, subcategory]
Index: []

[0 rows x 89 columns]

In [40]:
label_counts_12 = analyze_labels_in_dataframe(tagged_df_12)
print("Resultados del análisis del DataFrame:")
for column, counts in label_counts_12.items():
    print(f"Column: {column}")
    for label, count in counts.items():
        print(f"  {label}: {count}")

Resultados del análisis del DataFrame:
Column: attack
Column: category
Column: subcategory

### Data Theft N°13

In [41]:
# Procesar etiquetado de DataFrames
tagged_df_13 = process_tagging(reference_df, df_to_label_13, "Bot-IoT", config)
tagged_df_13.head(5)

2024-12-22 13:35:15 - csv_processor - INFO - Iniciando proceso de etiquetado...
2024-12-22 13:35:15 - csv_processor - INFO - Iniciando el proceso de etiquetado...
2024-12-22 13:35:15 - csv_processor - INFO - Operando los DataFrames...
2024-12-22 13:35:15 - csv_processor - INFO - Proceso de etiquetado completado.

Empty DataFrame
Columns: [id, expiration_id, src_ip, src_mac, src_oui, src_port, dst_ip, dst_mac, dst_oui, dst_port, protocol, ip_version, vlan_id, tunnel_id, bidirectional_first_seen_ms, bidirectional_last_seen_ms, bidirectional_duration_ms, bidirectional_packets, bidirectional_bytes, src2dst_first_seen_ms, src2dst_last_seen_ms, src2dst_duration_ms, src2dst_packets, src2dst_bytes, dst2src_first_seen_ms, dst2src_last_seen_ms, dst2src_duration_ms, dst2src_packets, dst2src_bytes, bidirectional_min_ps, bidirectional_mean_ps, bidirectional_stddev_ps, bidirectional_max_ps, src2dst_min_ps, src2dst_mean_ps, src2dst_stddev_ps, src2dst_max_ps, dst2src_min_ps, dst2src_mean_ps, dst2src_stddev_ps, dst2src_max_ps, bidirectional_min_piat_ms, bidirectional_mean_piat_ms, bidirectional_stddev_piat_ms, bidirectional_max_piat_ms, src2dst_min_piat_ms, src2dst_mean_piat_ms, src2dst_stddev_piat_ms, src2dst_max_piat_ms, dst2src_min_piat_ms, dst2src_mean_piat_ms, dst2src_stddev_piat_ms, dst2src_max_piat_ms, bidirectional_syn_packets, bidirectional_cwr_packets, bidirectional_ece_packets, bidirectional_urg_packets, bidirectional_ack_packets, bidirectional_psh_packets, bidirectional_rst_packets, bidirectional_fin_packets, src2dst_syn_packets, src2dst_cwr_packets, src2dst_ece_packets, src2dst_urg_packets, src2dst_ack_packets, src2dst_psh_packets, src2dst_rst_packets, src2dst_fin_packets, dst2src_syn_packets, dst2src_cwr_packets, dst2src_ece_packets, dst2src_urg_packets, dst2src_ack_packets, dst2src_psh_packets, dst2src_rst_packets, dst2src_fin_packets, application_name, application_category_name, application_is_guessed, application_confidence, requested_server_name, client_fingerprint, server_fingerprint, user_agent, content_type, attack, category, subcategory]
Index: []

[0 rows x 89 columns]

In [42]:
label_counts_13 = analyze_labels_in_dataframe(tagged_df_13)
print("Resultados del análisis del DataFrame:")
for column, counts in label_counts_13.items():
    print(f"Column: {column}")
    for label, count in counts.items():
        print(f"  {label}: {count}")

Resultados del análisis del DataFrame:
Column: attack
Column: category
Column: subcategory